version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: noladevs
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nola-devs:
    depends_on:
      - mongo
    ports:
      - '4173:4173'
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
